'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3643
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''trocasenha class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class trocasenha

	'''<summary>
	'''frmSTA control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents frmSTA As Global.System.Web.UI.HtmlControls.HtmlForm

	'''<summary>
	'''txtEmail control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtSenha control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtSenha As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtNovaSenha control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtNovaSenha As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtNovaSenhaR control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtNovaSenhaR As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnSubmit control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''lblErro control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblErro As Global.System.Web.UI.WebControls.Label
End Class
