'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3643
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''consultasexternas class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class consultasexternas

	'''<summary>
	'''frmSTA control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents frmSTA As Global.System.Web.UI.HtmlControls.HtmlForm

	'''<summary>
	'''lblErro control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblErro As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''trAdminTit control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents trAdminTit As Global.System.Web.UI.HtmlControls.HtmlTableRow

	'''<summary>
	'''trAdminCampos control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents trAdminCampos As Global.System.Web.UI.HtmlControls.HtmlTableRow

	'''<summary>
	'''txtNome control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtNome As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''cboTipo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cboTipo As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''chkValidados control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents chkValidados As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''chkExcluidos control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents chkExcluidos As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''btnConsultar control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnConsultar As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''dtgRegistros control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dtgRegistros As Global.System.Web.UI.WebControls.DataGrid
End Class
