'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3643
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''consultasinternas class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class consultasinternas

	'''<summary>
	'''codFornecedor control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents codFornecedor As Global.System.Web.UI.HtmlControls.HtmlInputHidden

	'''<summary>
	'''txtNome control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtNome As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtDataInicial control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtDataInicial As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnCalInicial control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnCalInicial As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''txtDataFinal control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtDataFinal As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnCalFinal control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnCalFinal As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnConsultar control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnConsultar As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''dtgRegistros control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dtgRegistros As Global.System.Web.UI.WebControls.DataGrid

	'''<summary>
	'''lblErro control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblErro As Global.System.Web.UI.WebControls.Label
End Class
