'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3643
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''popcalendario class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class popcalendario

	'''<summary>
	'''frmPMQ control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents frmPMQ As Global.System.Web.UI.HtmlControls.HtmlForm

	'''<summary>
	'''calData control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents calData As Global.System.Web.UI.WebControls.Calendar
End Class
