'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3643
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''popfornecedor class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class popfornecedor

	'''<summary>
	'''frmSTA control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents frmSTA As Global.System.Web.UI.HtmlControls.HtmlForm

	'''<summary>
	'''lblErro control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblErro As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''txtCodigo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtCodigo As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''TxtNome control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TxtNome As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtDiretorio control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtDiretorio As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtCNPJCPF control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtCNPJCPF As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''TxtEmail control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TxtEmail As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''TxtTelefone control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TxtTelefone As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtResponsavel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtResponsavel As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtPassword control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtPassword As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtMailResponsavel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtMailResponsavel As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtExtensoes control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtExtensoes As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''chkMantem control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents chkMantem As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''codFornecedor control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents codFornecedor As Global.System.Web.UI.HtmlControls.HtmlInputHidden

	'''<summary>
	'''hidExclusao control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidExclusao As Global.System.Web.UI.HtmlControls.HtmlInputHidden

	'''<summary>
	'''hidDiretorio control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidDiretorio As Global.System.Web.UI.HtmlControls.HtmlInputHidden

	'''<summary>
	'''btnSubmit control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnExcluir control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnExcluir As Global.System.Web.UI.HtmlControls.HtmlInputButton
End Class
