'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3643
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''usuupload class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class usuupload

	'''<summary>
	'''htitulo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents htitulo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''frmSTA control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents frmSTA As Global.System.Web.UI.HtmlControls.HtmlForm

	'''<summary>
	'''tabelaTipoEnvio control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tabelaTipoEnvio As Global.System.Web.UI.HtmlControls.HtmlTable

	'''<summary>
	'''linhaTipoEnvio control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents linhaTipoEnvio As Global.System.Web.UI.HtmlControls.HtmlTableRow

	'''<summary>
	'''btnInterno control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnInterno As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''btnFornecedores control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnFornecedores As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''btnTemporaria control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnTemporaria As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''dtgDestinos control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dtgDestinos As Global.System.Web.UI.WebControls.DataGrid

	'''<summary>
	'''dtgArquivos control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dtgArquivos As Global.System.Web.UI.WebControls.DataGrid

	'''<summary>
	'''DivMensagem control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents DivMensagem As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''txtMensagem control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtMensagem As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''trComandosMailArquivo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents trComandosMailArquivo As Global.System.Web.UI.HtmlControls.HtmlTableRow

	'''<summary>
	'''btnMail control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnMail As Global.System.Web.UI.HtmlControls.HtmlInputImage

	'''<summary>
	'''btnArquiv control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnArquiv As Global.System.Web.UI.HtmlControls.HtmlInputImage

	'''<summary>
	'''trComandosConfirmacao control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents trComandosConfirmacao As Global.System.Web.UI.HtmlControls.HtmlTableRow

	'''<summary>
	'''btnCancelar control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnCancelar As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''btnConfirmar control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnConfirmar As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lblErro control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblErro As Global.System.Web.UI.WebControls.Label
End Class
